#!/bin/zsh

export BASE=$(dirname $0)
BASE=${BASE:a}
cd $BASE && git pull origin master

manifest=(
    .tmux.conf
    .zshenv
    .zshrc
    .vimrc
    .ncmpcpp/config
    .zsh
    .xmonad/xmonad.hs
    bin
)

relink () {
    real=$BASE/$1
    real=${real:a}
    new=$HOME/$1
    newdir=${new:h}
    [[ -d $newdir ]] || mkdir -p $newdir
    [[ -h $new ]] && unlink $new
    [[ -f $new ]] && rm $new
    ln -s $real $new && echo "linked $new -> $real"
}

[[ -f $BASE/../.tmux.hotkey ]] || cp $BASE/.tmux.hotkey.sample $BASE/../.tmux.hotkey

git submodule init; git submodule update
git submodule foreach git pull origin master;

for x in $manifest
do
    relink $x
done

source ~/.zshrc
